"""add last_completed_at to trigger_state

Revision ID: 08547ae7dc0b
Revises: 395210f62428
Create Date: 2026-07-20 07:09:35.114242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08547ae7dc0b'
down_revision: Union[str, Sequence[str], None] = '395210f62428'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trigger_state', sa.Column('last_completed_at', sa.String(), nullable=True))
    op.create_index(op.f('ix_trigger_state_last_completed_at'), 'trigger_state', ['last_completed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trigger_state_last_completed_at'), table_name='trigger_state')
    op.drop_column('trigger_state', 'last_completed_at')
    # ### end Alembic commands ###
