"""add trigger_state table

Revision ID: 395210f62428
Revises: f192c20efc16
Create Date: 2026-07-20 05:27:47.549705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '395210f62428'
down_revision: Union[str, Sequence[str], None] = 'f192c20efc16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trigger_state',
    sa.Column('pipeline_id', sa.String(), nullable=False),
    sa.Column('last_triggered_at', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('pipeline_id')
    )
    op.create_index(op.f('ix_trigger_state_last_triggered_at'), 'trigger_state', ['last_triggered_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trigger_state_last_triggered_at'), table_name='trigger_state')
    op.drop_table('trigger_state')
    # ### end Alembic commands ###
