"""add narrator persona link fields (persona_feature_plan_v3.md Phase3 §3.5)

nazokake_itemsへ、語り手ペルソナ(narrator persona)へのFK制約なし論理参照4列を
追加する。Firestore(narrator_personas/narrator_persona_versions、Phase4で新設
予定)をSSoTとするための橋渡し列。SQLiteのため render_as_batch=True 経由の
batch_alter_table(新テーブル作成→コピー→差し替え)で安全にADD/DROPする。

Revision ID: 7cef352f0e11
Revises: b3e8f2a1c7d9
Create Date: 2026-08-12 17:28:10.248426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cef352f0e11'
down_revision: Union[str, Sequence[str], None] = 'b3e8f2a1c7d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nazokake_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('narrator_persona_id', sa.String(), server_default='No_Data', nullable=False))
        batch_op.add_column(sa.Column('narrator_persona_version_id', sa.String(), server_default='No_Data', nullable=False))
        batch_op.add_column(sa.Column('narrator_persona_name', sa.String(), server_default='No_Data', nullable=False))
        batch_op.add_column(sa.Column('data_origin', sa.String(), server_default='no_data', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('nazokake_items', schema=None) as batch_op:
        batch_op.drop_column('data_origin')
        batch_op.drop_column('narrator_persona_name')
        batch_op.drop_column('narrator_persona_version_id')
        batch_op.drop_column('narrator_persona_id')

    # ### end Alembic commands ###
