"""Initial schema

Revision ID: 9a00e26d93a7
Revises: 
Create Date: 2026-07-16 19:33:38.925655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a00e26d93a7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('target_item_id', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('reason', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_target_item_id'), 'audit_logs', ['target_item_id'], unique=False)
    op.create_table('nazokake_items',
    sa.Column('doc_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=True),
    sa.Column('odai', sa.String(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('nazokake_text', sa.Text(), nullable=True),
    sa.Column('scores', sa.JSON(), nullable=True),
    sa.Column('s_total', sa.Float(), nullable=True),
    sa.Column('overall', sa.Text(), nullable=True),
    sa.Column('axis_comments', sa.JSON(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('evaluated_at', sa.String(), nullable=True),
    sa.Column('result_gemini', sa.JSON(), nullable=True),
    sa.Column('llmjp_status', sa.String(), nullable=True),
    sa.Column('result_llmjp', sa.JSON(), nullable=True),
    sa.Column('nazokake_text_llmjp', sa.Text(), nullable=True),
    sa.Column('scores_llmjp', sa.JSON(), nullable=True),
    sa.Column('s_total_llmjp', sa.Float(), nullable=True),
    sa.Column('overall_llmjp', sa.Text(), nullable=True),
    sa.Column('axis_comments_llmjp', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('model_id', sa.String(), nullable=True),
    sa.Column('evaluator_model_id', sa.String(), nullable=True),
    sa.Column('persona', sa.JSON(), nullable=True),
    sa.Column('trend', sa.JSON(), nullable=True),
    sa.Column('dpo_pair_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('schema_version', sa.String(), nullable=True),
    sa.Column('feed_ready', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('eval_status', sa.String(), nullable=True),
    sa.Column('is_user_edited', sa.Boolean(), nullable=False),
    sa.Column('is_golden_data', sa.Boolean(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('random_weight', sa.Float(), nullable=True),
    sa.Column('gemini_status', sa.String(), nullable=True),
    sa.Column('elyza_status', sa.String(), nullable=True),
    sa.Column('locked_at', sa.String(), nullable=True),
    sa.Column('completed_at', sa.String(), nullable=True),
    sa.Column('result_doc_ids', sa.JSON(), nullable=True),
    sa.Column('human_evaluations', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('sync_status', sa.String(), nullable=False),
    sa.Column('last_sync_error', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('doc_id')
    )
    op.create_index(op.f('ix_nazokake_items_status'), 'nazokake_items', ['status'], unique=False)
    op.create_index(op.f('ix_nazokake_items_sync_status'), 'nazokake_items', ['sync_status'], unique=False)
    op.create_index(op.f('ix_nazokake_items_updated_at'), 'nazokake_items', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nazokake_items_updated_at'), table_name='nazokake_items')
    op.drop_index(op.f('ix_nazokake_items_sync_status'), table_name='nazokake_items')
    op.drop_index(op.f('ix_nazokake_items_status'), table_name='nazokake_items')
    op.drop_table('nazokake_items')
    op.drop_index(op.f('ix_audit_logs_target_item_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
