"""add research_articles table

Revision ID: ac5c6cd8803f
Revises: 0beb78c386a3
Create Date: 2026-07-26 11:12:31.633671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac5c6cd8803f'
down_revision: Union[str, Sequence[str], None] = '0beb78c386a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('research_articles',
    sa.Column('article_id', sa.String(), nullable=False),
    sa.Column('main_category', sa.String(), nullable=False),
    sa.Column('sub_category', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('article_id')
    )
    op.create_index(op.f('ix_research_articles_main_category'), 'research_articles', ['main_category'], unique=False)
    op.create_index(op.f('ix_research_articles_sub_category'), 'research_articles', ['sub_category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_research_articles_sub_category'), table_name='research_articles')
    op.drop_index(op.f('ix_research_articles_main_category'), table_name='research_articles')
    op.drop_table('research_articles')
    # ### end Alembic commands ###
