"""Add trained_at coreset replay tracking column

Revision ID: f192c20efc16
Revises: 9a00e26d93a7
Create Date: 2026-07-17 05:53:33.506102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f192c20efc16'
down_revision: Union[str, Sequence[str], None] = '9a00e26d93a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nazokake_items', sa.Column('trained_at', sa.String(), nullable=True))
    op.create_index(op.f('ix_nazokake_items_trained_at'), 'nazokake_items', ['trained_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nazokake_items_trained_at'), table_name='nazokake_items')
    op.drop_column('nazokake_items', 'trained_at')
    # ### end Alembic commands ###
